services:
  - type: web
    name: ecommerce-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r ecommerce_backend/requirements.txt
    startCommand: |
      cd ecommerce_backend &&
      gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    autoDeploy: true
