services:
  - type: web
    name: alx-project-nexus
    env: python
    region: oregon
    plan: starter

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ecommerce_backend.ecommerce.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_backend.ecommerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
